### ISSUE TITLE
Shell do not really work after using Pyinstaller

### ISSUE THREAD

**Issue by Hawax** [Y4hL/PyDoor#1]
**C:\Users\xxxxxx\AppData\Roaming>dir
Connection lost: InvalidToken: (line 92)**

Maybe it's import error or something dunno. Everything else works great :)

**Comment by Y4hL** [comment]
Can you tell me how you could replicate this issue ( parameters for compiling exe and what version you are using ) and the version of the client.py that you are using

**Comment by Hawax** [comment]
The problem is caused probably by using parameter --noconsole in pyinstaller, without this everything, works fine :).

my pyinstaller options "pyinstaller --onefile  .\client.py --noconsole "

I'm using python 3.7.6 and pyinstaller 3.6.
I also see in log in client after using pyinstaller 

"client.py:412: DeprecationWarning: The Windows bytes API has been deprecated, use Unicode filenames instead" maybe its important.

Python interpreter works excellent 👯

**Comment by Y4hL** [comment]
If cx_freeze works fine, I think I'll just keep it at that. Debugging without a console in pyinstaller seems like quite the hassle.

**Comment by Y4hL** [comment]
@Hawax This got fixed in a recent commit. The problem was not giving subprocesses a stdin. This, when compiled to an exe would break the client. Here's the [commit](https://github.com/Y4hL/PyDoor/commit/a26531edb67a891c10cbf11b4478ade7249748d3).

**Comment by Hawax** [comment]
@Y4hL amazing I'm glad you fixed that "bug"  🥇
