### ISSUE TITLE
Traceback (most recent call last):   File "setup.py", line 2, in <module>     from cx_Freeze import setup, Executable ImportError: No module named cx_Freeze

### ISSUE THREAD

**Issue by Neoneoexe** [Y4hL/PyDoor#10]
I am getting the following error, I dont think you included the from files in the git repo...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from cx_Freeze import setup, Executable
ImportError: No module named cx_Freeze

**Comment by Y4hL** [comment]
I don’t have cx_Freeze as a requirement as it is not required to run the project. A simple ”pip install cx_Freeze” should do the trick
