### ISSUE TITLE
Nothing Happening

### ISSUE THREAD

**Issue by asdat3** [Y4hL/PyDoor#11]
Hey,

I just tried the stuff
after launching the .exe nothing happens
in the log it says that the client started, nothing else
but I am getting no connection on the server

pretty sure the stuff is set correctly, both files are attached

I also checked the firewall of my server (linux server) and it doesnt block port 8000 so I dont see the issue
I also tryed launching the client.py and nothing happened, it prints out nothing and it doesnt close or anything
[upload.zip](https://github.com/Y4hL/PyDoor/files/6843300/upload.zip)

**Comment by Y4hL** [comment]
Hey @asdat3 
Are you using tools like ngrok or dataplicity to open your linux server to the web or have you only written your external IP in the client.
The problem is most likely the setup of your server.

**Comment by asdat3** [comment]
Just entered the public ip of the server (ending on .231)

I will have a look in ngrok in a sec.
 Just woke up

**Comment by asdat3** [comment]
IDK, makes no sense I will just try to get some output in the client.py

**Comment by asdat3** [comment]
Hey,
I am very sorry
I added the debugging stuff and it turned out to be a connection refused, my server firewall still closed port 8000

it's now working fine, thanks :D
