### ISSUE TITLE
unresolved references

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [Y4hL/PyDoor#13]
import file ```client.modules.persistance``` missing in this repo? (import used in client.py)
import file ```cx_Freeze``` missing in this repo (import used in setup.py)

**Comment by Y4hL** [comment]
client.modules.persistance does exist under the modules subfolder, is it throwing you an error when you run the client? cx_Freeze is an extra dependency that is not required, that is used to compile the client if wanted. It can be installed using "pip install --upgrade cx_Freeze"

**Comment by kaliiiiiiiiii** [comment]
Thanks for your fast Answer!
