### ISSUE TITLE
Cant get connection

### ISSUE THREAD

**Issue by PinkPantherX** [Y4hL/PyDoor#14]
Tried everything but just can't get a connection..
Can you make a video or step to step guide please.
I didnt even compiled exe file, but even python file doesn't connect

**Comment by Y4hL** [comment]
Are you running both the client and server locally?

**Comment by Y4hL** [comment]
Does your VPS have a public IP address that is open to the internet? There's probably some error with the configuration.

**Comment by PinkPantherX** [comment]
It has. All opened..

**Comment by Y4hL** [comment]
Does pinging your server work?

**Comment by PinkPantherX** [comment]
Works. Just tried

**Comment by PinkPantherX** [comment]
On client-server.py just changed from 8001 to 4444.
And on client.py added vps ip adress and changed to 4444

**Comment by PinkPantherX** [comment]
> On client-server.py just changed from 8001 to 4444. And on client.py added vps ip adress and changed to 4444

I mean server.cli.py

**Comment by Y4hL** [comment]
If the connection work, the only other reason I could see why no connections show up is if the handshake between them fails. Could you change logging.CRITICAL to logging.DEBUG in first few lines of the server. And for the client the same thing. Now the server should be printing out debug messages and the clients log also. Check if you see anything unusual there.
