### ISSUE TITLE
Connection lost: InvalidToken: (line 85)

### ISSUE THREAD

**Issue by assafd** [Y4hL/PyDoor#2]
After compiling to EXE, you cannot run CMD commands - the following error occurs:

> --i 0
You are now connected to DESKTOP-TEST
127.0.0.1> --e
C:\Users\tets\Downloads\PyDoor-master\PyDoor-master\Client\output>ipconfig
Connection lost: InvalidToken: (line 85)
>

**Comment by Y4hL** [comment]
Could you check the log of the client for error messages and did you use cx_freeze or pyinstaller

**Comment by Y4hL** [comment]
Wrote a bug fix that should have solved it. Try it again and tell me if it works.

**Comment by assafd** [comment]
Thanks, Let me know once you fixed it

**Comment by Y4hL** [comment]
It should be working now, auto-py-to-exe uses pyinstaller, so my fix should work for that aswell

**Comment by assafd** [comment]
Working well! thanks
