### ISSUE TITLE
Standalone executable

### ISSUE THREAD

**Issue by mandroid19** [Y4hL/PyDoor#6]
Hi, 
First of all thanks for the program. I tried it with my vms and it works great. However I realized that the client works only if the 178MB lib directory is present at the same location. Could you please make it work without needing to download the 178mb lib file next to the client.exe? Thank you in advance

**Comment by Y4hL** [comment]
Using the `--onefile` argument in [pyinstaller](https://pypi.org/project/PyInstaller/) you can create a standalone exe with no additional files. Pyinstaller isn't the default compile method, because of this: https://stackoverflow.com/a/5497896/10625567
