### ISSUE TITLE
Help!!!!

### ISSUE THREAD

**Issue by emprrr** [Y4hL/PyDoor#8]
problem with the interface, after the appearance of the connection with the client, the program does not go beyond MENU_HELP, what should I do?
![IMG20201111223131](https://user-images.githubusercontent.com/74320591/98850169-c5976280-246d-11eb-89be-34a158c1ba4a.jpg)

**Comment by Y4hL** [comment]
After the connection to the client has been established, you need to "connect" to it using the "--i" command followed by the connection ID (when using --l the first number, in your case 0). Example "--i 0". Then you can use the --e command to open a shell or --h to see all commands

**Comment by emprrr** [comment]
thanks a lot, I'm still very stupid in python, thanks again
